# Influx Database name k8s
# user root pass root
version: '3'
services:
  influxdb:
    image: tutum/influxdb
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ifdata:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083      
  grafana:
    image: grafana/grafana:latest
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
    ports:
      - 3000:3000
      
volumes:
  ifdata:
    driver: local 
