# Influx Database name k8s
# user root pass root
version: '3'
services:
  influxdb:
    image: tutum/influxdb
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ifdata:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083      
  grafana:
    image: tutum/grafana
    deploy:
      restart_policy:
        condition: any
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - INFLUXDB_PROTO=http                 
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086                  
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root
    ports:
      - 3000:80
      
volumes:
  ifdata:
    driver: local 
